// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mywebproject_core.Data;

namespace Mywebproject_core.Migrations
{
    [DbContext(typeof(CandidateDetailContext))]
    partial class CandidateDetailContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Mywebproject_core.Models.CandidateDetail", b =>
                {
                    b.Property<string>("candidate_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("candidate_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("party")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("candidate_id");

                    b.ToTable("CandidateDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
